---
swagger: "2.0"
info:
  version: "2017-01-12T12:53:53Z"
  title: "<your api name>"
host: ""
basePath: "/Prod"
schemes:
- "https"
paths:
  /webhook:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "X-Github-Event"
        in: "header"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\n  \"github_event\": \"$input.params('X-Github-Event')\"\
            ,\n  \"body_json\": $input.json('$')\n}\n"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/<your lambda's arn>/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
